- index.ipynb
- public/classes.json
- src/components/CalloutCard.astro
- src/components/Section.astro
- src/components/Sidebar.svelte
- src/components/SubSection.astro
- src/components/SubSubSection.astro
- src/layouts/Layout.astro
- src/pages/sta/cartesian_coordinates.astro
- src/pages/sta/centers_of_mass.astro
- src/pages/sta/forcesystems.astro
- src/pages/sta/free_body_diagrams.astro
- src/pages/sta/friction.astro
- src/pages/sta/hydrostatic_fluid_pressure.astro
- src/pages/sta/internal_forces.astro
- src/pages/sta/introduction.astro
- src/pages/sta/moment_of_inertia.astro
- src/pages/sta/moments.astro
- src/pages/sta/reaction_forces.astro
- src/pages/sta/trusses.astro
- src/pages/sta/vectors_scalars.astro
- src/pages/sta/virtual_work.astro
- tex_to_astro.ipynb
changed layout/section system to include side column for side cards, added card element
> layout changes

- CNAME
- README.md
- astro.config.mjs
- public/CNAME
Changed config and README to reflect the change from http://www.mechref.org => http://mechref.org.
> Tweaks to DNS config

- public/static/js/simplified_view.js
- src/components/CardGrid.svelte
- src/layouts/Layout.astro
- src/pages/[course].astro
Made simplified view the default, disabled switching to "fancy" view.
Added course title to page, as it isnt obvious which course we are currently viewing the pages for.
Made font bigger when on small screens as text was too small, leading to potential misclicks.
> Course content page tweaks

- src/layouts/Layout.astro
The tag here is associated with an analytics account that I set up.
> Add Google analytics

- src/pages/sta/reaction_forces.astro
I'm waiting to update this until tomorrow (Saturday 10/12) so that we don't confuse any 211 students who are taking the quiz today.
> Update reaction_forces.astro - wait until 10/12!!

- README.md
- package-lock.json
- src/env.d.ts
- src/pages/sol/transverse_shear.astro
Fixed typo on transverse shear webpage from "followling" to "following".
> Typo on transverse shear webpage

- mechref
- src/pages/dyn/particle_kinematics.astro
- src/pages/dyn/particle_kinetics.astro
- src/pages/dyn/rigid_body_kinematics.astro
- src/pages/dyn/rigid_body_kinetics.astro
- src/pages/dyn/vector_calculus.astro
Added captions to external images and fixed broken links. Added sections to have "smooth scrolling" when the user needs to transition to another section by clicking on a hyperlink. Still need to verify some other links.
> Changes to particle kinetics, rigid body kinematics and kinetics

- src/pages/about.astro
Changed ordering of links on About us Page
> oshat task 219 About Us page changes

- src/layouts/Layout.astro
adds description prop to Layout element, allows for making page descriptions in Layout element
i.e. Layout title = "example" description = "This is an example page"/
> adds description prop to Layout element

- public/about/docs.js
adds js code that the style guide astro file is trying to call
addresses [this issue.](https://github.com/IllinoisRef/mechref/issues/234)
> style guide prairiedraw fix

- src/components/Navbar.astro
- src/pages/dyn/contact_and_rolling.astro
- src/pages/dyn/particle_kinematics.astro
- src/pages/dyn/particle_kinetics.astro
- src/pages/dyn/rigid_body_kinematics.astro
- src/pages/dyn/rigid_body_kinetics.astro
- src/pages/dyn/vector_calculus.astro
- src/pages/dyn/vectors.astro
- src/pages/dyn/work_and_energy.astro
standardized navtree  and subsection sentence case usage
-put everything into sentencing case
-indented subsubsections that were not in navtrees
-made sure every navtree link was present and working (left out application subsub...sections for space)
> 212 Navtree // sentencing case

- public/dyn/particle_kinematics/canvases.js
- src/pages/dyn/particle_kinematics.astro
- src/pages/sol/material_properties.astro
> particle kinematics to rbk and pva heads up call out cards

- src/pages/sta/force_systems.astro
- src/pages/sta/hydrostatic_fluid_pressure.astro
Addresses this [this issue.](https://github.com/IllinoisRef/mechref/issues/248)
> dist. loads / hydrostatics callout cards

- src/components/Navbar.astro
- src/pages/sta.astro
- src/pages/sta/internal_forces.astro
Addresses #148
-renames the page to "Internal forces" everywhere
-replaces right arrows with "results in" in summary table
> Internal forces rework

- public/about/docs.js
- public/dyn/contact_and_rolling/canvases.js
- public/dyn/particle_kinematics/canvases.js
- public/dyn/rigid_body_kinematics/canvases.js
- public/dyn/rigid_body_kinetics/canvases.js
- public/dyn/work_and_energy/canvases.js
- public/sta/introduction/canvases.js
- public/sta/vectors_scalars/canvases.js
- src/pages/dyn/particle_kinematics.astro
Addresses #211
Addresses #242 (for statics and dynamics)
> #211 and #242 fixes

- src/pages/sta.astro
> statics apps list

- src/pages/dyn/rigid_body_kinetics.astro
overlapping cards in rbkinetics fixed
> callout card fix

- src/components/Navbar.astro
adds applications to the navbar for statics and dynamics
> applications in navbar

- src/pages/dyn/introduction.astro
- src/pages/sta/introduction.astro
for statics/dynamics part of #319
> #319 statics/dynamics table

- src/pages/sol.astro
To resolve issue #306, all the images have been reverted to regular text with links to their respective topic.
> Solid Homepage Revert

- src/pages/sta/introduction.astro
for the first bullet of #310
- removes assumptions in statics subheading
- adds vertical line to table
- vertically centers contents
> What is statics?

- src/pages/dyn/introduction.astro
- src/pages/sta/introduction.astro
for the first bullet of #316 
- removes assumptions in dynamics subheading
- adds vertical line to table
- vertically centers contents
> what is dynamics?

- src/pages/dyn/coordinate_systems.astro
> Cylindrical Coordinates Warning Box
